windowrulev2 = float, class:engrampa
windowrulev2 = suppressevent, maximize, class:libreoffice
windowrulev2 = maximize, title:(.* - RustDesk)
windowrulev2 = workspace 6 silent, float, class:hyprland-share-picker

bezier = linear, 0, 0, 0, 0
animation = layers, 1, 2, linear

layerrule = match:namespace calendar, animation slide 
layerrule = match:namespace calendar, order -1 

layerrule = match:namespace app-launcher, animation slide
layerrule = match:namespace app-launcher, order 1

layerrule = match:namespace remove-device, animation slide top 
layerrule = match:namespace remove-device, order -1 
